### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by T0071** [Marten4n6/EvilOSX#11]
Exception happened during processing of request from ('XXX.XXX.XX.XXX', XXXXX)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/root/EvilOSX/server/controller.py", line 177, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
root@ubuntu:~# python EvilOSX/server/server.py

**Comment by Marten4n6** [comment]
You should run `python server/server.py` when you're in the EvilOSX directory.
Let me know if this fixes the issue, if not please post the server version you are using since I'm unable to replicate this issue.
