### ISSUE TITLE
ModuleNotFoundError: No module named 'Cryptodome'

### ISSUE THREAD

**Issue by YasirAsim** [Marten4n6/EvilOSX#123]
Hello, I'm using window 10, While executing "python start.py" command I got this error.

C:\Users\FAST COMPUTER\EvilOSX>python start.py
Traceback (most recent call last):
  File "start.py", line 13, in <module>
    from server.handler import start_server
  File "C:\Users\FAST COMPUTER\EvilOSX\server\handler.py", line 22, in <module>
    from server import modules
  File "C:\Users\FAST COMPUTER\EvilOSX\server\modules\__init__.py", line 11, in <module>
    from server.modules.helper import ModuleABC
  File "C:\Users\FAST COMPUTER\EvilOSX\server\modules\helper.py", line 10, in <module>
    from server.model import Model
  File "C:\Users\FAST COMPUTER\EvilOSX\server\model.py", line 11, in <module>
    from Cryptodome.Cipher import AES
ModuleNotFoundError: No module named 'Cryptodome'

Can you please help me to solve this issue?

**Comment by Wolfoverflow** [comment]
pip install pycryptodome==3.10.1 pycryptodomex==3.8.1

**Comment by Wolfoverflow** [comment]
Happy coding!

**Comment by ghost** [comment]
I had the same problem but now it works tx Wolfoverflow!

**Comment by Wolfoverflow** [comment]
Np!
