### ISSUE TITLE
'NoneType' object has no attribute 'put'

### ISSUE THREAD

**Issue by federico22285** [Marten4n6/EvilOSX#14]
First of all, thank you for your efforts in creating this cute RAT!. 

I would like to ask what could be the reason of getting constantly the following error message when trying to use practically "any" module. 

```
use browser_history
```
```
I hit enter twice, nothing happens and the error below is thrown at me.
```
```
[?] Server port to listen on: 2228
Traceback (most recent call last):
  File "server/server.py", line 546, in <module>
    main()
  File "server/server.py", line 541, in main
    view.run()
  File "server/server.py", line 495, in run
    self._main_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1116, in keypress
    return self.footer.keypress((maxcol,),key)
  File "server/server.py", line 127, in keypress
    self._queue.put(command)
AttributeError: 'NoneType' object has no attribute 'put'
```

**Comment by Marten4n6** [comment]
Thanks for letting me know! The issue is in the changes I made in [this commit](https://github.com/Marten4n6/EvilOSX/commit/a474aa704d454af803a0ce9a7c047f835d1a7abc).
