### ISSUE TITLE
2.1.6 - macOS Sierra 10.12.16 - webcam module - AssertionError: rows, render mismatch

### ISSUE THREAD

**Issue by federico22285** [Marten4n6/EvilOSX#15]
```
run the server
```

```
use webcam  module
```

```
The following exception it is shown
```

```
For testing, I have executed the agent on the target as root and also as a local user. 
```

```
[?] Server port to listen on: 2228
Traceback (most recent call last):
  File "server/server.py", line 545, in <module>
    main()
  File "server/server.py", line 540, in main
    view.run()
  File "server/server.py", line 494, in run
    self._main_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 710, in _loop
    self._entering_idle()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 671, in _entering_idle
    callback()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 564, in entering_idle
    self.draw_screen()
  File "server/server.py", line 50, in draw_screen
    super(SafeMainLoop, self).draw_screen()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 578, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1096, in render
    assert foot.rows() == frows, "rows, render mismatch"
AssertionError: rows, render mismatch
root@kali:~/hacking/EvilOSX#
```

**Comment by Marten4n6** [comment]
Can you let me know if the latest version (2.1.6) fixes this?

**Comment by federico22285** [comment]
Hi I just updated the title. This is happening in the latest version 2.1.6

**Comment by Marten4n6** [comment]
It works for me (using the webcam module or any other module), can you remove your EvilOSX directory then download this repository again?

**Comment by federico22285** [comment]
```
root@kali:~/hacking# rm -rf EvilOSX/
root@kali:~/hacking# git clone https://github.com/Marten4n6/EvilOSX
Cloning into 'EvilOSX'...
remote: Counting objects: 228, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 228 (delta 10), reused 16 (delta 6), pack-reused 203
Receiving objects: 100% (228/228), 121.84 KiB | 674.00 KiB/s, done.
Resolving deltas: 100% (126/126), done.
root@kali:~/hacking# cp server.* EvilOSX/
root@kali:~/hacking# cd EvilOSX/
root@kali:~/hacking/EvilOSX# python server/server.py
```
```
use webcam  ( confirm selection [Y]

```
```
[?] Server port to listen on: 2228
Traceback (most recent call last):
  File "server/server.py", line 546, in <module>
    main()
  File "server/server.py", line 541, in main
    view.run()
  File "server/server.py", line 495, in run
    self._main_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 710, in _loop
    self._entering_idle()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 671, in _entering_idle
    callback()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 564, in entering_idle
    self.draw_screen()
  File "server/server.py", line 50, in draw_screen
    super(SafeMainLoop, self).draw_screen()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 578, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1096, in render
    assert foot.rows() == frows, "rows, render mismatch"
AssertionError: rows, render mismatch
```

**Comment by federico22285** [comment]
```
Module webcam:
[!] A green LED will show next to the client's camera (for about a second).
[!] This module also touches the disk.
[?] Are you sure you want to continue? [Y/n]
```
It seems that at the moment I enter [Y] the mentioned exception is happening. 

I never get to enter the path as it is showing in the webcam.py module 

```
if not confirm or confirm == "y":
            self.output_folder = os.path.expanduser(module_view.prompt("Local output folder (ENTER for output/): "))
```

**Comment by Marten4n6** [comment]
Hello, sorry for the long delay.
Can you let me know if you experience anything related to this issue in the latest version?
Note that the server side now uses python3.
Thanks.
