### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by marvic2409** [Marten4n6/EvilOSX#44]
I made the server to be on ubuntu 16.4 and it gives me an error: [!] Failed to print fancy banner, skipping... 

I decided to continue and when I put in the script without the clear and terminal closing I get these errors:
Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1412, in read
    return s + self._file.read(amt - len(s))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
socket.error: [Errno 54] Connection reset by peer

**Comment by marvic2409** [comment]
Im stupid, nvm
