### ISSUE TITLE
sql issues after Pull 

### ISSUE THREAD

**Issue by ipkstef** [Marten4n6/EvilOSX#73]
Traceback (most recent call last):
  File "start.py", line 169, in <module>
    main()
  File "start.py", line 149, in main
    model = Model()
  File "/home/ubuntu/EvilOSX/server/model.py", line 96, in __init__
    self._cursor.execute("DROP TABLE IF EXISTS bots")
sqlite3.OperationalError: attempt to write a readonly database

**Comment by Marten4n6** [comment]
Try deleting the database file then restart the server.

**Comment by ipkstef** [comment]
Deleting the DB file worked in fixing the issue with server starting. But now the Screenshot Module is returning error:   

Module Server Error:
Incorrect padding

perhaps an issue with the base64 decoding?

**Comment by ipkstef** [comment]
solved

**Comment by tinamina12** [comment]
how did you solve this?

**Comment by criticalmiind** [comment]
> Try deleting the database file then restart the server.

How to delete database file can u guide me please

**Comment by GLGRA** [comment]
> solved

I’m having the same issue: “incorrect padding”. How did you make it work?.

**Comment by ipkstef** [comment]
Oh man it’s been 2 years I don’t remember tbh
