### ISSUE TITLE
Unable to startup the bot

### ISSUE THREAD

**Issue by ev3rest** [Marten4n6/EvilOSX#79]
```User@mbp ~> python Launcher-c2d41b.py 
User@mbp ~> [DEBUG] <module>:26 - Program directory: /Users/User/Library/Containers/.XVwKRmXuJ
[DEBUG] <module>:27 - Launch agent name: evilosx
[DEBUG] <module>:28 - Payload filename: ZkBbnjk
Traceback (most recent call last):
  File "<stdin>", line 24, in <module>
  File "<string>", line 79, in <module>
IOError: [Errno 2] No such file or directory: '/Users/User/Library/Containers/.XVwKRmXuJ/ZkBbnjk' 
```

Any ideas on what can cause this?

**Comment by ev3rest** [comment]
Meanwhile, server is printing this: ```Creating encrypted payload using key: …```

**Comment by iSansei** [comment]
read my post same issue
