### ISSUE TITLE
ImportError: No module named http.server

### ISSUE THREAD

**Issue by MaxTCodes** [Marten4n6/EvilOSX#82]
When I try to do the command "python start.py" I get the error 
"Traceback (most recent call last):
  File "start.py", line 13, in <module>
    from server.handler import start_server
  File "/Users/admin/EvilOSX/server/handler.py", line 13, in <module>
    from http.server import HTTPServer, BaseHTTPRequestHandler
ImportError: No module named http.server"
How do I fix this?

**Comment by ghost** [comment]
Same Problem. I did some research, and I found http.server is for python3. But the command, "pip3 install -r requirements.txt" and running it with Python3 didn't fix the problem. Any Fixes?

**Comment by HaK5aw** [comment]
Did anyone ever figure this out?

**Comment by MaxTCodes** [comment]
Nope, I just reinstalled it and it worked. I think it's a glitch where PIP skips it, I'm unsure though.

**Comment by HaK5aw** [comment]
I did pip3 install and python3 start.py. Make sure you're in the correct directory, otherwise you'll have to type/the/entire/path.
